# Site settings
author: Loi Dinh
title: An entrepreneur's journey to become a Full Stack Web Developer.
header-img: img/home-bg.png
email: liamphatdinh@gmail.com
copyright_name: Loi Dinh
description: > # this means to ignore newlines until "baseurl:"
  A dairy of how one learning to be a Web Developer 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  LiamDinh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
